#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         FileHandle-Unget
version:      0.15
version_from: lib/FileHandle/Unget.pm
installdirs:  site
requires:
    Scalar::Util:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
